# Generated by Django 4.1.2 on 2022-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='', max_length=200, verbose_name='Текст'),
        ),
    ]
