# Generated by Django 4.1.2 on 2022-10-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Пол')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='information',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Информация о пользователе'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sex_accounts', to='accounts.sex', verbose_name='Пол'),
        ),
    ]
