# Generated by Django 4.1.2 on 2022-10-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sex_account_information_account_phone_account_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='sex',
            name='title_rus',
            field=models.CharField(default='', max_length=10, verbose_name='Пол (рус)'),
        ),
    ]
