# Generated by Django 4.1.2 on 2022-10-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sex_title_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sex',
            name='title_rus',
            field=models.CharField(max_length=10, verbose_name='Пол (рус)'),
        ),
    ]
