# Generated by Django 4.1.2 on 2022-10-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_liked_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='liked_posts',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscriptions',
        ),
    ]
