# Generated by Django 4.1.2 on 2022-11-01 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
